# Location of top-level MicroPython directory
MPY_DIR = ../../../../../../..
#Assuming the makefile is located at /home/sjaak/Documents/micropython/micropython/ports/esp32/boards/LOLIN_S2_MINI/modules/micropython_perlin/natmod/Makefile

# Name of module
MOD = factorial

# Source files (.c or .py)
SRC = factorial.c

# Architecture to build for (x86, x64, armv7m, xtensa, xtensawin)
ARCH = xtensawin

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk
